# AIcarus Napcat Adapter - 配置文件模板
# 版本号用于跟踪配置结构的变化。
# 当此模板的结构发生重大更改时，请务必更新此版本号。
config_version = "1.0.0" # 初始版本号

[adapter_server]
host = "127.0.0.1" # Adapter 监听来自 Napcat 客户端连接的 IP 地址。 '0.0.0.0' 表示监听所有可用网络接口。
port = 8078      # Adapter 监听来自 Napcat 客户端连接的端口。

[core_connection]
url = "ws://127.0.0.1:8077/ws"  # 你的 AIcarus Core WebSocket 服务器的完整 URL。请确保 Core 服务器已启动并监听此地址。
platform_id = "napcat_qq_bot_instance_1" # 此 Adapter 实例在 Core 处注册的唯一标识符。用于 Core 区分不同的 Adapter 连接。

[bot_settings]
nickname = "" # 可选：机器人的昵称。如果不需要，请将其值保留为空字符串 "" 或直接删除此行。
napcat_heartbeat_interval_seconds = 30 # Adapter 与 Napcat 客户端之间心跳检查的间隔秒数 (如果 Adapter 需要实现此逻辑)。

# [another_section] # 示例：未来可能添加的新配置段
# new_setting = "default_value"
